<?xml version="1.0" encoding="utf-8"?><Database Name="ReklamaDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PAWEL-KOMPUTER\SQLEXPRESS;Initial Catalog=ReklamaDB;Integrated Security=True" SettingsObjectName="BazyDanych.Properties.Settings" SettingsPropertyName="ReklamaDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Klient" Member="Klients">
    <Type Name="Klient">
      <Column Name="KlientID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NIP" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Nazwa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Adres" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Klient_Faktura" Member="Fakturas" ThisKey="KlientID" OtherKey="KlientID" Type="Faktura" />
      <Association Name="Klient_Reklamacja" Member="Reklamacjas" ThisKey="KlientID" OtherKey="KlientID" Type="Reklamacja" />
      <Association Name="Klient_Zlecenie" Member="Zlecenies" ThisKey="KlientID" OtherKey="KlientID" Type="Zlecenie" />
    </Type>
  </Table>
  <Table Name="dbo.Pracownik" Member="Pracowniks">
    <Type Name="Pracownik">
      <Column Name="PracownikID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Imie" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Nazwisko" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Adres" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Stanowisko" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Pracownik_Faktura" Member="Fakturas" ThisKey="PracownikID" OtherKey="PracownikID" Type="Faktura" />
      <Association Name="Pracownik_PracownikWSkladzie" Member="PracownikWSkladzies" ThisKey="PracownikID" OtherKey="PracownikID" Type="PracownikWSkladzie" />
      <Association Name="Pracownik_Reklamacja" Member="Reklamacjas" ThisKey="PracownikID" OtherKey="PracownikID" Type="Reklamacja" />
      <Association Name="Pracownik_Zespol" Member="Zespols" ThisKey="PracownikID" OtherKey="KierownikID" Type="Zespol" />
      <Association Name="Pracownik_Zlecenie" Member="Zlecenies" ThisKey="PracownikID" OtherKey="PracownikID" Type="Zlecenie" />
    </Type>
  </Table>
  <Table Name="dbo.Bilboard" Member="Bilboards">
    <Type Name="Bilboard">
      <Column Name="LokalizacjaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SzerokoscGeograficzna" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="DlugoscGeograficzna" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="IloscReklam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Lokalizacja_Bilboard" Member="Lokalizacja" ThisKey="LokalizacjaID" OtherKey="LokalizacjaID" Type="Lokalizacja" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Branza" Member="Branzas">
    <Type Name="Branza">
      <Column Name="BranzaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nazwa" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Branza_ReklamaZBranzy" Member="ReklamaZBranzies" ThisKey="BranzaID" OtherKey="BranzaID" Type="ReklamaZBranzy" />
    </Type>
  </Table>
  <Table Name="dbo.Budynek" Member="Budyneks">
    <Type Name="Budynek">
      <Column Name="LokalizacjaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Adres" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Lokalizacja_Budynek" Member="Lokalizacja" ThisKey="LokalizacjaID" OtherKey="LokalizacjaID" Type="Lokalizacja" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Faktura" Member="Fakturas">
    <Type Name="Faktura">
      <Column Name="FakturaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NumerFaktury" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DataWystawienia" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DataSprzedazy" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="TerminPlatnosci" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Zaplacona" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="KlientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PracownikID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SposobPlatnosci" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Faktura_ZleceniaNaFakturze" Member="ZleceniaNaFakturzes" ThisKey="FakturaID" OtherKey="FakturaID" Type="ZleceniaNaFakturze" />
      <Association Name="Klient_Faktura" Member="Klient" ThisKey="KlientID" OtherKey="KlientID" Type="Klient" IsForeignKey="true" />
      <Association Name="Pracownik_Faktura" Member="Pracownik" ThisKey="PracownikID" OtherKey="PracownikID" Type="Pracownik" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ogordzenie" Member="Ogordzenies">
    <Type Name="Ogordzenie">
      <Column Name="LokalizacjaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SzerokoscGeograficzna" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="DlugoscGeograficzna" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="IloscReklam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ulica" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="Lokalizacja_Ogordzenie" Member="Lokalizacja" ThisKey="LokalizacjaID" OtherKey="LokalizacjaID" Type="Lokalizacja" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PracownikWSkladzie" Member="PracownikWSkladzies">
    <Type Name="PracownikWSkladzie">
      <Column Name="SkladID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PracownikID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Pracownik_PracownikWSkladzie" Member="Pracownik" ThisKey="PracownikID" OtherKey="PracownikID" Type="Pracownik" IsForeignKey="true" />
      <Association Name="Sklad_PracownikWSkladzie" Member="Sklad" ThisKey="SkladID" OtherKey="SkladID" Type="Sklad" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reklamacja" Member="Reklamacjas">
    <Type Name="Reklamacja">
      <Column Name="ReklamacjaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DataWystawienia" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Tresc" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="PracownikID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KlientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Klient_Reklamacja" Member="Klient" ThisKey="KlientID" OtherKey="KlientID" Type="Klient" IsForeignKey="true" />
      <Association Name="Pracownik_Reklamacja" Member="Pracownik" ThisKey="PracownikID" OtherKey="PracownikID" Type="Pracownik" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReklamaZBranzy" Member="ReklamaZBranzies">
    <Type Name="ReklamaZBranzy">
      <Column Name="ReklamaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BranzaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Branza_ReklamaZBranzy" Member="Branza" ThisKey="BranzaID" OtherKey="BranzaID" Type="Branza" IsForeignKey="true" />
      <Association Name="Reklama_ReklamaZBranzy" Member="Reklama" ThisKey="ReklamaID" OtherKey="ReklamaID" Type="Reklama" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sklad" Member="Sklads">
    <Type Name="Sklad">
      <Column Name="SkladID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ZespolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Sklad_PracownikWSkladzie" Member="PracownikWSkladzies" ThisKey="SkladID" OtherKey="SkladID" Type="PracownikWSkladzie" />
      <Association Name="Zespol_Sklad" Member="Zespol" ThisKey="ZespolID" OtherKey="ZespolID" Type="Zespol" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SlupOgloszeniowy" Member="SlupOgloszeniowies">
    <Type Name="SlupOgloszeniowy">
      <Column Name="LokalizacjaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SzerokoscGeograficzna" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="DlugoscGeograficzna" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="IloscReklam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Lokalizacja_SlupOgloszeniowy" Member="Lokalizacja" ThisKey="LokalizacjaID" OtherKey="LokalizacjaID" Type="Lokalizacja" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tramwaj" Member="Tramwajs">
    <Type Name="Tramwaj">
      <Column Name="LokalizacjaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Linia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Trasa" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Lokalizacja_Tramwaj" Member="Lokalizacja" ThisKey="LokalizacjaID" OtherKey="LokalizacjaID" Type="Lokalizacja" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Zespol" Member="Zespols">
    <Type Name="Zespol">
      <Column Name="ZespolID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KierownikID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Zespol_Sklad" Member="Sklads" ThisKey="ZespolID" OtherKey="ZespolID" Type="Sklad" />
      <Association Name="Zespol_Realizacja" Member="Realizacjas" ThisKey="ZespolID" OtherKey="ZespolID" Type="Realizacja" />
      <Association Name="Pracownik_Zespol" Member="Pracownik" ThisKey="KierownikID" OtherKey="PracownikID" Type="Pracownik" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZleceniaNaFakturze" Member="ZleceniaNaFakturzes">
    <Type Name="ZleceniaNaFakturze">
      <Column Name="FakturaID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ZlecenieID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Faktura_ZleceniaNaFakturze" Member="Faktura" ThisKey="FakturaID" OtherKey="FakturaID" Type="Faktura" IsForeignKey="true" />
      <Association Name="Zlecenie_ZleceniaNaFakturze" Member="Zlecenie" ThisKey="ZlecenieID" OtherKey="ZlecenieID" Type="Zlecenie" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Zlecenie" Member="Zlecenies">
    <Type Name="Zlecenie">
      <Column Name="ZlecenieID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PracownikID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KlientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReklamaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TerminRozpoczecia" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="TerminZakonczenia" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="StanZlecenia" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="Zlecenie_ZleceniaNaFakturze" Member="ZleceniaNaFakturzes" ThisKey="ZlecenieID" OtherKey="ZlecenieID" Type="ZleceniaNaFakturze" />
      <Association Name="Klient_Zlecenie" Member="Klient" ThisKey="KlientID" OtherKey="KlientID" Type="Klient" IsForeignKey="true" />
      <Association Name="Pracownik_Zlecenie" Member="Pracownik" ThisKey="PracownikID" OtherKey="PracownikID" Type="Pracownik" IsForeignKey="true" />
      <Association Name="Reklama_Zlecenie" Member="Reklama" ThisKey="ReklamaID" OtherKey="ReklamaID" Type="Reklama" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Realizacja" Member="Realizacjas">
    <Type Name="Realizacja">
      <Column Name="RealizacjaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReklamaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ZespolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Realizacja_RealizacjaWLokalizacji" Member="RealizacjaWLokalizacjis" ThisKey="RealizacjaID" OtherKey="RealizacjaID" Type="RealizacjaWLokalizacji" />
      <Association Name="Zespol_Realizacja" Member="Zespol" ThisKey="ZespolID" OtherKey="ZespolID" Type="Zespol" IsForeignKey="true" />
      <Association Name="Reklama_Realizacja" Member="Reklama" ThisKey="ReklamaID" OtherKey="ReklamaID" Type="Reklama" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reklama" Member="Reklamas">
    <Type Name="Reklama">
      <Column Name="ReklamaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Opis" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Wysokosc" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Szerokosc" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="Reklama_ReklamaZBranzy" Member="ReklamaZBranzies" ThisKey="ReklamaID" OtherKey="ReklamaID" Type="ReklamaZBranzy" />
      <Association Name="Reklama_Zlecenie" Member="Zlecenies" ThisKey="ReklamaID" OtherKey="ReklamaID" Type="Zlecenie" />
      <Association Name="Reklama_Realizacja" Member="Realizacjas" ThisKey="ReklamaID" OtherKey="ReklamaID" Type="Realizacja" />
      <Association Name="Reklama_ReklamaWLokalizacji" Member="ReklamaWLokalizacjis" ThisKey="ReklamaID" OtherKey="ReklamaID" Type="ReklamaWLokalizacji" />
    </Type>
  </Table>
  <Table Name="dbo.Lokalizacja" Member="Lokalizacjas">
    <Type Name="Lokalizacja">
      <Column Name="LokalizacjaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Opis" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NIP" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Wysokosc" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Szerokosc" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="WolneMiejsce" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="Lokalizacja_Bilboard" Member="Bilboards" ThisKey="LokalizacjaID" OtherKey="LokalizacjaID" Type="Bilboard" />
      <Association Name="Lokalizacja_Budynek" Member="Budyneks" ThisKey="LokalizacjaID" OtherKey="LokalizacjaID" Type="Budynek" />
      <Association Name="Lokalizacja_Ogordzenie" Member="Ogordzenies" ThisKey="LokalizacjaID" OtherKey="LokalizacjaID" Type="Ogordzenie" />
      <Association Name="Lokalizacja_SlupOgloszeniowy" Member="SlupOgloszeniowies" ThisKey="LokalizacjaID" OtherKey="LokalizacjaID" Type="SlupOgloszeniowy" />
      <Association Name="Lokalizacja_Tramwaj" Member="Tramwajs" ThisKey="LokalizacjaID" OtherKey="LokalizacjaID" Type="Tramwaj" />
      <Association Name="Lokalizacja_RealizacjaWLokalizacji" Member="RealizacjaWLokalizacjis" ThisKey="LokalizacjaID" OtherKey="LokalizacjaID" Type="RealizacjaWLokalizacji" />
      <Association Name="Lokalizacja_ReklamaWLokalizacji" Member="ReklamaWLokalizacjis" ThisKey="LokalizacjaID" OtherKey="LokalizacjaID" Type="ReklamaWLokalizacji" />
    </Type>
  </Table>
  <Table Name="dbo.RealizacjaWLokalizacji" Member="RealizacjaWLokalizacjis">
    <Type Name="RealizacjaWLokalizacji">
      <Column Name="RealizacjaID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LokalizacjaID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Lokalizacja_RealizacjaWLokalizacji" Member="Lokalizacja" ThisKey="LokalizacjaID" OtherKey="LokalizacjaID" Type="Lokalizacja" IsForeignKey="true" />
      <Association Name="Realizacja_RealizacjaWLokalizacji" Member="Realizacja" ThisKey="RealizacjaID" OtherKey="RealizacjaID" Type="Realizacja" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReklamaWLokalizacji" Member="ReklamaWLokalizacjis">
    <Type Name="ReklamaWLokalizacji">
      <Column Name="ReklamaID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LokalizacjaID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Wspolrzedna_X" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Wspolrzedna_Y" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="Lokalizacja_ReklamaWLokalizacji" Member="Lokalizacja" ThisKey="LokalizacjaID" OtherKey="LokalizacjaID" Type="Lokalizacja" IsForeignKey="true" />
      <Association Name="Reklama_ReklamaWLokalizacji" Member="Reklama" ThisKey="ReklamaID" OtherKey="ReklamaID" Type="Reklama" IsForeignKey="true" />
    </Type>
  </Table>
</Database>